### ISSUE TITLE
Which `reasoning` is currently included in the data?

### ISSUE THREAD

**Issue by okhat** [xlang-ai/BRIGHT#4]
Awesome work, folks! In the data structure, you include:

```
- query: the query for retrieval
- reasoning: the required reasoning to retrieve documents
```

The paper discusses generating the reasoning via many LLMs, like GPT-4 or others. Which LM is involved in the released data?

**Comment by hongjin-su** [comment]
Thanks a lot for the question! The `reasoning` field in the released dataset is annotated by humans and is not used in any experiment throughout the paper.

**Comment by okhat** [comment]
Thank you! That makes sense and should probably be clarified because it’s an important detail

**Comment by hongjin-su** [comment]
Feel free to re-open the issue if you have further questions!
