### ISSUE TITLE
Question about Submitting to BRIGHT Leaderboard

### ISSUE THREAD

**Issue by WolfNiu** [xlang-ai/BRIGHT#7]
I wonder if there is a way to submit only to the BRIGHT leaderboard. 
Asking this because the ranking and models on the MTEB leaderboard (with the BRIGHT tab) (https://huggingface.co/spaces/mteb/leaderboard) look quite different from those on the BRIGHT leaderboard (https://brightbenchmark.github.io/), and the MTEB version also doesn't have the "long document" tab. Thanks!

**Comment by hongjin-su** [comment]
Hi! Thanks for your interest!

If you would like to submit your results to the leaderboard, email both your code (will be kept confidential in our side) and results to [suhongjin96@gamil.com](mailto:%20suhongjin96@gamil.com)!

**Comment by hongjin-su** [comment]
Replied in the email! If the code is proprietary, it is possible to only share the results with brief descriptions on models and methods!

**Comment by Muennighoff** [comment]
Thanks for raising! I've added a new tab for the long document variant: https://huggingface.co/spaces/mteb/leaderboard?task=retrieval&language=bright

The remaining difference is that the MTEB leaderboard does not include submissions with reasoning steps & reranking atm. It would be great to include them! For that I think we will need to ensure that evaluation in these two settings works in mteb 
 & we need to add filters/separate tabs for each I think (similar to how we allow filtering out CrossEncoders for e.g. the FollowIR (Retrieval w/ Instructions) tab) 🤔
