### ISSUE TITLE
pos doc may have a problem

### ISSUE THREAD

**Issue by xiewen354** [xlang-ai/BRIGHT#9]
Hello author, I was looking at the Bright dataset and found some problems about the pos document. Some documents are full of html links, while others contain only one word. There are also more than 30 positive example documents corresponding to query, but many of these are artificially irrelevant. Take for example # 0 and # last of psychology.

Would you mind re-filtering the data?

![image](https://github.com/user-attachments/assets/4a48d58d-f19e-466c-95b6-d80f6e0a6fa8)
![image](https://github.com/user-attachments/assets/df461348-ea7d-46af-a2cd-dc9078b9afae)

**Comment by hongjin-su** [comment]
Thanks a lot for your post!

In the corpus of each dataset, there is a lot of irrelevant information including URLs, single words and random documents (as you show above), and they are counted as negative documents.

In the positive documents to each query, most of them are valid sentences or paragraphs. We perform another round of examination and correct a small portion of examples.

Hope this helps!
